package fullerton.lfg.database

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "profile_table")
data class Profile(
    // Defines the table's primary key. Primary keys are unique values that can be autogenerated.
    // They are used to differentiate one entity from another.
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "profile_id")
    var profileId: Int = 0,

    // Non-primary key column. Data type is specified in the property.
    @ColumnInfo(name = "first_name")
    var firstname: String = "",

    // Non-primary key column. Data type is specified in the property.
    @ColumnInfo(name = "last_name")
    var lastname: String = "",

    // Non-primary key column. Data type is specified in the property.
    @ColumnInfo(name = "email")
    var email: String = "",

    // Non-primary key column. Data type is specified in the property.
    @ColumnInfo(name = "password")
    var password: String = ""
)
